/*
 * Copyright (C) 2013 Red Hat, Inc.
 * Written by Florian Weimer <fweimer@redhat.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <cxxll/os.hpp>

#include <errno.h>
#include <stdio.h>

// Includes constants generated by GCC.

const char *
cxxll::error_string_or_null(int code) throw()
{
#define check(x) if (code == x) return #x;
#include "error-constants.inc"
#undef check
  return nullptr;
}

std::string
cxxll::error_string(int code)
{
  const char *errstr = error_string_or_null(code);
  if (errstr != nullptr) {
    return errstr;
  }
  char buf[64];
  snprintf(buf, sizeof(buf), "ERROR(%d)", code);
  return buf;
}

std::string
cxxll::error_string()
{
  return error_string(errno);
}
